version: "3.1"
services:
  spring-app:
    image: spring-boot-dashboard:latest
    environment:
      - JAVA_OPTS=-Xms128M -Xmx256M
    ports:
      - "8080:8080"
  ea-datasource:
    image:  ea-datasource:latest
    environment:
      - JAVA_OPTS=-Xms128M -Xmx256M
    ports:
      - "8083:8083"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
      - GF_USERS_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
    ports:
      - "3000:3000"
    depends_on:
      - prometheus