version: "3.1"
services:
  spring-app:
    image: spring-boot-dashboard:latest
    environment:
      - JAVA_OPTS=-Xms128M -Xmx256M
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3.8.2-management
    ports:
      - "5672:5672"
      - "15692:15692"
    command: rabbitmq-plugins enable rabbitmq_prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
