apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
    # don't set this to true in production
    editable: true

  - name: SimpleJson
    type: grafana-simple-json-datasource
    access: proxy
    isDefault: false
    url: http://ea-datasource:8083
    # don't set this to true in production
    editable: true